### ISSUE TITLE
Fix: typo in project2.jl

### ISSUE THREAD

**Issue by tashakim** [sisl/AA222Project2_2020#3]
There is a typo in: https://github.com/sisl/AA222Project2/blob/master/project2_jl/project2.jl#L2C1-L3C1
where `project1.jl` (line 2 ) should be `project2.jl`

**Comment by dylan-asmar** [comment]
Thanks for catching this @tashakim !
Fixed with 4282bcf734de713333bdfe0fd12209cb59efa0cc
